# Generated by Django 4.2.4 on 2024-08-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_candidate_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
