# Generated by Django 4.2.4 on 2024-09-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
