# Generated by Django 4.2.4 on 2024-09-16 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Поиск исполнителя', 'Поиск исполнителя'), ('В процессе', 'В процессе'), ('Выполнена', 'Выполнена')], default='Поиск исполнителя', max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('type', models.CharField(choices=[('Исполнительная документация', 'Исполнительная документация'), ('Проектная/рабочая документация', 'Проектная/рабочая документация'), ('ПОС', 'ПОС'), ('ППР/ППРК', 'ППР/ППРК'), ('Геодезия', 'Геодезия')], default='Исполнительная документация', max_length=200)),
                ('category', models.CharField(choices=[('Земля', 'Земля'), ('Канашка', 'Канашка'), ('Вода', 'Вода'), ('Электрика', 'Электрика')], default='Земля', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='searchwork.task')),
            ],
        ),
    ]
