# Generated by Django 4.2.4 on 2024-08-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchwork', '0002_task_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
