# Generated by Django 4.2.4 on 2024-08-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchwork', '0003_task_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
