# Generated by Django 4.2.4 on 2023-08-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchwork', '0003_task_worker_alter_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Поиск исполнителя', 'Поиск исполнителя'), ('В процессе', 'В процессе'), ('Выполнена', 'Выполнена')], default='Актуальна', max_length=200),
        ),
    ]
