# Generated by Django 4.2.4 on 2024-08-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchwork', '0004_alter_task_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Земля', 'Земля'), ('Канашка', 'Канашка'), ('Вода', 'Вода'), ('Электрика', 'Электрика')], default='Исполнительная документация', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Исполнительная документация', 'Исполнительная документация'), ('Проектная/рабочая документация', 'Проектная/рабочая документация'), ('ПОС', 'ПОС'), ('ППР/ППРК', 'ППР/ППРК'), ('Геодезия', 'Геодезия')], default='Земля', max_length=200),
            preserve_default=False,
        ),
    ]
