# Generated by Django 4.2.4 on 2023-08-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchwork', '0004_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Поиск исполнителя', 'Поиск исполнителя'), ('В процессе', 'В процессе'), ('Выполнена', 'Выполнена')], default='Поиск исполнителя', max_length=200),
        ),
    ]
